name = "test6"
main = "src/optimized.js"
compatibility_date = "2025-06-20"


[[d1_databases]]
binding = "DB"
database_name = "test6-mines"
database_id = "2c3e85c7-c603-418f-a4e8-0a64957cdfd6"

[env.production]
name = "test6"
